[internal]
exten => _10XX,1,Dial(PJSIP/${EXTEN},60)
exten => _10XX,n,Playback(vm-nobodyavail)
exten => _10XX,n,Hangup()

; Conference Room 9000 
exten => 9000,1,Answer()
exten => 9000,n,Playback(enter-password)
exten => 9000,n,Read(PIN,,4,,1,5)
exten => 9000,n,GotoIf($["${PIN}"="1234"]?conf)
exten => 9000,n,Playback(vm-goodbye)
exten => 9000,n,Hangup()

exten => 9000,n(conf),ConfBridge(9000)
exten => 9000,n,Hangup()
